### ISSUE TITLE
Docker image won't start

### ISSUE THREAD

**Issue by HumungusTheLord** [tonlabs/ton-q-server#315]
Trying to start Dockerfile. Get an error:

`node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module './dist/server'
Require stack:
- /home/node/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/node/index.js:17:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/node/index.js' ]
}

Node.js v18.15.0
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module './dist/server'
Require stack:
- /home/node/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/node/index.js:17:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/node/index.js' ]
}

Node.js v18.15.0
`

**Comment by HumungusTheLord** [comment]
With docker command: `RUN nmp run tsc` get an error:


#0 3.643 error TS2688: Cannot find type definition file for 'jest'.#0 3.643   The file is in the program because:
#0 3.643     Entry point of type library 'jest' specified in compilerOptions

**Comment by Artem-Zhdanov** [comment]
To run q-server in docker do the following:
1. Compile source files
```
npm install
npm run tsc
```
2. Build docker image
```
docker build . -t qserver
```
3.  Q-server requires ArangoDB to run on HTTP port 8901.\
The easiest way to start ArangoDB is as written in the README:
```
$ everdev se start
$ everdev se set --db-port 8901
```
Wait a bit (sometimes it takes up to 2 minutes) and check if the ArangoDB web interface is available at http://localhost:8901.

3. Create and run a new container )(change 192.168.122.1 to your IP address)
```
docker run --rm -d \
    -p 4000:4000 \
    -e Q_REQUESTS_MODE=rest \
    -e Q_REQUESTS_SERVER=192.168.122.1 \
    -e Q_DATA_MUT=http://192.168.122.1:8901 \
    -e Q_DATA_HOT=http://192.168.122.1:8901 \
  qserver
```
GraphQL playground must be available on http://localhost:4000/graphql

**Comment by HumungusTheLord** [comment]
It works now.

You have to change documentation: typing `npm install ` is not enough to start q-server, because it won't create the dist directory. So we need both commands: 
- `npm install`
- `npm run tsc` ( for regenerating the ``dist`` folder https://github.com/tonlabs/ton-q-server#for-developers)

Also docker template should be changed to something like this:

```
FROM node:18-buster
RUN mkdir -p /q-server
WORKDIR /q-server
ADD ton-q-server .
RUN npm install
RUN npm run tsc
EXPOSE 4000
ENTRYPOINT ["node", "index.js"]
```
